AdminSiteUseMVC/Controllers/Admin/AdminAccount/AdminAccountController.cs
using AdminSiteUseMVC.Models.IRepository.Admin;
using AdminSiteUseMVC.Models.Services.Email;
using AdminSiteUseMVC.Models.Services.UserEmailOption;
using AdminSiteUseMVC.ViewModel.Admin;
using Domian;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminSiteUseMVC.Controllers.Admin.AdminAccount
{
    public class AdminAccountController : Controller
    {
        private readonly UserManager<User> _adminManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IEmailService _emailService;
        private readonly IConfiguration _configuration;

        // private readonly IUserService _userService;

        // private readonly IAdminAccountRepository _adminAccountRepository;

        public AdminAccountController(UserManager<User> adminManager, RoleManager<Role> roleManager,SignInManager<User> signInManager,IEmailService emailService,IConfiguration configuration)//, IAdminAccountRepository adminAccountRepository)
        {
             _adminManager = adminManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _emailService = emailService;
            _configuration = configuration;
            // _userService = userService;
            // _adminAccountRepository = adminAccountRepository;
        }
     
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
      
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> SignUp([FromForm] RegistrationModel registrationModel)
        //{
        //  if(!ModelState.IsValid)
        //        return View(registrationModel);
        //    try
        //    {
        //        if (await _adminManager.FindByEmailAsync(registrationModel.Email) != null)
        //        {
        //            ModelState.AddModelError(string.Empty, "Email Is Already Registered!");
        //            return View(registrationModel);
        //        }

        //        if (await _adminManager.FindByNameAsync(registrationModel.UserName) != null)
        //        {
        //            ModelState.AddModelError(string.Empty, "UserName Is Already Registered!");
        //            return View(registrationModel);
        //        }
        //        User _user = registrationModel.ToModel();
        //        var result = await _adminManager.CreateAsync(_user, registrationModel.Password);
        //        if (!result.Succeeded)
        //        {
        //            //var errors = string.Empty;
        //            foreach (var error in result.Errors)
        //            {
        //                //errors += $"{error.Description},";
        //                ModelState.AddModelError(string.Empty, error.Description);
        //            }

        //            return View(registrationModel);
        //        }
        //       await _signInManager.SignInAsync(_user, true);

        //        await _adminManager.AddToRoleAsync(_user, "Admin");
        //        return RedirectToAction("Index", "Home");

        //    }
        //    catch(Exception ex)
        //    {
        //        ModelState.AddModelError(string.Empty, ex.Message);
        //        return View(registrationModel);
        //    }
        //}
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([FromForm] RegistrationModel registrationModel)
         {
            if (!ModelState.IsValid)
                return View(registrationModel);
            try
            {
                if (await _adminManager.FindByEmailAsync(registrationModel.Email) != null)
                {
                    ModelState.AddModelError(string.Empty, "Email Is Already Registered!");
                    return View(registrationModel);
                }

                if (await _adminManager.FindByNameAsync(registrationModel.UserName) != null)
                {
                    ModelState.AddModelError(string.Empty, "UserName Is Already Registered!");
                    return View(registrationModel);
                }
                User _user = registrationModel.ToModel();
                var result = await _adminManager.CreateAsync(_user, registrationModel.Password);
                if (result.Succeeded)
                {
                    await _adminManager.AddToRoleAsync(_user, "Admin");
                    var token = await _adminManager.GenerateEmailConfirmationTokenAsync(_user);
                    if(!string.IsNullOrEmpty(token))
                    {
                       await SendEmailConfirmationEmail(_user, token);
                    }
                    return View(nameof(GOToEmailToConfirm));
                    //return View (registrationModel);
                    
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        //errors += $"{error.Description},";
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                    return View(registrationModel);

                }
             

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(registrationModel);
            }
        }
        [HttpGet]
        public IActionResult GOToEmailToConfirm()
        {
            return View();
        }

        [HttpGet("confirm-email")]
        public async Task<IActionResult> ConfirmEmail(int id, string token)
        {
          
            if (id!=null && !string.IsNullOrEmpty(token))
            {
                token = token.Replace(' ', '+');
                var result = await _adminManager.ConfirmEmailAsync(await _adminManager.Users.FirstOrDefaultAsync(u=>u.Id==id), token);
                if (result.Succeeded)
                {
                  return  RedirectToAction(nameof(LogIN));
                   // ViewBag.ISSuccess = true;
                }
            }

            return View();
        }
    


        //public async Task<IActionResult> SignUp([FromBody] RegistrationModel registrationModel)
        //{
        //    if (!ModelState.IsValid)
        //        return BadRequest(ModelState);
        //    string resulat = await _adminAccountRepository.Registration(registrationModel);
        //    if (resulat.Equals("Email Is Already Registered!"))
        //        return BadRequest(resulat);
        //    else if (resulat.Equals("UserName Is Already Registered!"))
        //        return BadRequest(resulat);
        //    return Ok(resulat);

        //}
        // [Route("login")]
        [HttpGet]
        public IActionResult LogIN()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIN([FromForm] LoginModel loginModel)
        {
          if(!ModelState.IsValid)
                return View(loginModel);
            try
            {
                var _user = await _adminManager.FindByNameAsync(loginModel.UserName);


                if (_user is null || !await _adminManager.CheckPasswordAsync(_user, loginModel.Password))
                {
                    ModelState.AddModelError(string.Empty, "Email or Password is incorrect!");
                    return View(loginModel);

                }
                var result = await _signInManager.PasswordSignInAsync(loginModel.UserName, loginModel.Password, true, true);

                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(_user, loginModel.RememberMe);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login");
                    return View(loginModel);
                }

            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty,ex.Message);
                return View(loginModel);
            }
           
        }
        //public async Task<IActionResult> LogIN([FromBody] LoginModel loginModel)
        //{
        //    if (!ModelState.IsValid)
        //        return BadRequest(ModelState);
        //    string resulat = await _adminAccountRepository.Login(loginModel);
        //    if (resulat.Equals("Email or Password is incorrect!"))
        //        return BadRequest(resulat);

        //    return Ok(resulat);

        //}
        [HttpGet]
        public  IActionResult AddRole()
        {
            return View();
        }
       [HttpPost]
        public async Task<IActionResult> AddRole([FromBody] AddRoleModel addRoleModel)
        {
            var _user = await _adminManager.FindByIdAsync(addRoleModel.UserId.ToString());
            if (_user is null || !await _roleManager.RoleExistsAsync(addRoleModel.RoleName))
                return View("Invalid User Id or Role Nmae");

            if (await _adminManager.IsInRoleAsync(_user, addRoleModel.RoleName))
                return View("User already assigned to this role");

            var result = await _adminManager.AddToRoleAsync(_user, addRoleModel.RoleName);
            if (!result.Succeeded)
                return View("Sonething went wrong");

            return RedirectToAction("Index", "Home");

        }
        //public async Task<IActionResult> AddRoleAsync([FromBody] AddRoleModel model)
        //{
        //    if (!ModelState.IsValid)
        //        return BadRequest(ModelState);

        //    var result = await _adminAccountRepository.AddRoleAsync(model);

        //    if (!string.IsNullOrEmpty(result))
        //        return BadRequest(result);

AdminSiteUseMVC/Views/AdminAccount/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "ConfirmEmail";
}

<div class="container">
    <div class="row text-center">
        <div class="col-md-4">
          @*  @if (ViewBag.ISSuccess==true)
            {
                <div class="alert alert-success" role="alert">
                    <p>Your Email Has Been Verified Successfully.</p>

                </div>
            }
            else
            {*@
                <p>Somthing Went Wrong Or Your Token has Been Expired.</p>
           @* }*@
        

        </div>

    </div>

</div>

AdminSiteUseMVC/Views/AdminAccount/ForgotPassword.cshtml
@model AdminSiteUseMVC.ViewModel.Admin.ForgotPasswordModel
@inject IViewLocalizer localizer

@{
    ViewData["Title"] = "ForgotPassword";
}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-4">
            @if (Model?.EmailSent == true)
            {
                <div class="alert alert-success" role="alert">
                    <p>
                        @localizer["If You Are Registered With Us"], <br />
                        @localizer["We Have Sent An Email on Your Registered Email Id"]
                    </p>
                </div>
            }
            else
            {
                <p>@localizer["Forgot Your Password? No Worries You Can Reset It Easily."]</p>
                <form asp-action="ForgotPassword">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">@localizer["Continue"]</button>
                    </div>
                </form>
            }
            <div>
                <p>Back To<a asp-action="LogIN" asp-controller="AdminAccount">@localizer["Login"]</a></p>
            </div>
        </div>

    </div>
 </div>
    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminSiteUseMVC/Views/AdminAccount/GOToEmailToConfirm.cshtml
@{
    ViewData["Title"] = "GOToEmailToConfirm";
}

<div class="container">
    <div class="row text-center">
        <div class="col-md-4">
            @*  @if (ViewBag.ISSuccess==true)
            {
            <div class="alert alert-success" role="alert">
            <p>Your Email Has Been Verified Successfully.</p>

            </div>
            }
            else
            {*@
            <p>Go To EmailTo Confirm .</p>
            @* }*@


        </div>

    </div>

</div>

AdminSiteUseMVC/Views/AdminAccount/LogIN.cshtml
@model AdminSiteUseMVC.ViewModel.Admin.LoginModel

@{
    ViewData["Title"] = "LogIN";
}

<h1>LogIN</h1>

<h4>LoginModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="LogIN">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="RememberMe" /> @Html.DisplayNameFor(model => model.RememberMe)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminSiteUseMVC/Views/AdminAccount/ResetPassword.cshtml
@model AdminSiteUseMVC.ViewModel.Admin.ResetPasswordModel

@{
    ViewData["Title"] = "ResetPassword";
}
<div class="container">

    <h1 class="display-4">Reset password</h1>

    <hr />
    <div class="row">
        <div class="offset-4 col-md-4">
            @if (Model?.IsSuccess == true)
            {
                <div class="alert alert-success" role="alert">
                    <p>
                        You have updated your password successfully.
                    </p>
                </div>
            }
            else
            {
                <form asp-action="ResetPassword">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserId" class="form-control" />
                    <input type="hidden" asp-for="Token" class="form-control" />
                    <div class="form-group">
                        <label asp-for="NewPassword" class="control-label"></label>
                        <input asp-for="NewPassword" class="form-control" />
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmNewPassword" class="control-label"></label>
                        <input asp-for="ConfirmNewPassword" class="form-control" />
                        <span asp-validation-for="ConfirmNewPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Reset password" class="btn btn-primary" />
                    </div>
                </form>
            }

        </div>
    </div>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminSiteUseMVC/Views/AdminAccount/SignUp.cshtml
@model AdminSiteUseMVC.ViewModel.Admin.RegistrationModel

@{
    ViewData["Title"] = "SignUp";
}

<h1>SignUp</h1>

<h4>RegistrationModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SignUp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <p><a asp-action="ForgotPassword" asp-controller="AdminAccount">Login</a></p>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}